# Generated by Django 5.2.8 on 2025-11-27 06:13

import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingdocument",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=listings.models.listing_document_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="listingdocument",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listingphoto",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=listings.models.listing_photo_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="id_document",
            field=models.FileField(
                blank=True,
                help_text="Front photo of government ID",
                max_length=255,
                upload_to=listings.models.owner_id_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="ownerprofile",
            name="identity_reviewer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verificationrequest",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
